#pragma config(Motor,  port2,           RIGHT_TOP,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RIGHT_BOTTOM,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LEFT_BOTTOM,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LEFT_TOP,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           ARM_LEFT,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           ARM_RIGHT,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LAUNCHER,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ELEVATOR,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#define COMPETITION
#include "bot.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}
